name: Continuous Deployment
on: push

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dhall
        uses: dhall-lang/setup-dhall@v4
        with:
          version: '1.38.0'
      - name: Compile dhall -> html
        run: |
          mkdir -p out
          dhall text --file index.dhall --output out/index.html
          cp main.css index.gif favicon.ico out
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          branch: gh-pages
          folder: out
          clean: true
          clean-exclude: |
            CNAME
