name: Continuous Deployment
on: push

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Use Node 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm install --silent -g create-elm-app@5.22.0
      - run: elm-app build
      - name: Deploy to S3
        run: aws s3 sync ./build/ s3://autophagy.io --delete
